services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.myserver.local`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik-insecure.rule=Host(`traefik.myserver.local`)"
      - "traefik.http.routers.traefik-insecure.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://myserver.local,http://myserver.local"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mount the Docker socket so Traefik can listen to events
      - ./traefik:/etc/traefik # Mount the configuration folder

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  gethomepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: gethomepage
    environment:
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gethomepage.rule=Host(`myserver.local`)"
      - "traefik.http.routers.gethomepage.entrypoints=websecure"
      - "traefik.http.routers.gethomepage.tls=true"
      - "traefik.http.routers.gethomepage-insecure.rule=Host(`myserver.local`)"
      - "traefik.http.routers.gethomepage-insecure.entrypoints=web"
      - "traefik.http.services.gethomepage.loadbalancer.server.port=3000"
    volumes:
      - ./gethomepage/config:/app/config
      - ./gethomepage/images:/app/public/images
      - ./gethomepage/icons:/app/public/icons
    restart: always

networks:
  default:
    name: myserver
    external: true
