name: Labeling

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  pull-requests: write

jobs:
  call-labeling-workflow:
    uses: mauroalderete/workflows/.github/workflows/labeling.yml@v0
    secrets:
      github-token: ${{ secrets.GH_PROJECT_AUTOMATION }}
